name: tea_boy_crm
description: "Enterprise B2B Staffing CRM for Riyadh Corporate Offices supplying Cleaners, Pantry Staff, and Tea Boys"
publish_to: 'none'
version: 2.2.1+5

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  flutter_animate: ^4.5.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
