allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.22'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.22'
            force 'org.jetbrains.kotlin:kotlin-stdlib-common:1.9.22'
            force 'androidx.annotation:annotation:1.8.0'
            force 'androidx.annotation:annotation-jvm:1.8.0'
            force 'androidx.annotation:annotation-experimental:1.4.0'
            force 'androidx.core:core:1.13.1'
            force 'androidx.core:core-ktx:1.13.1'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
